export const GET_WIDGET_REQUEST = 'GET_WIDGET_REQUEST';
export const GET_WIDGET_SUCCESS = 'GET_WIDGET_SUCCESS';
export const GET_WIDGET_ERROR = 'GET_WIDGET_ERROR';

export const UPDATE_WIDGET_REQUEST = 'UPDATE_WIDGET_REQUEST';
export const UPDATE_WIDGET_SUCCES = 'UPDATE_WIDGET_SUCCES';
export const UPDATE_WIDGET_ERROR = 'UPDATE_WIDGET_ERROR';
