export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';

export const GET_ISSUE_REQUEST = 'GET_ISSUE_REQUEST';
export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCESS';
export const GET_ISSUE_ERROR = 'GET_ISSUE_ERROR';

export const UPDATE_ISSUE_REQUEST = 'UPDATE_ISSUE_REQUEST';
export const UPDATE_ISSUE_SUCCES = 'UPDATE_ISSUE_SUCCES';
export const UPDATE_ISSUE_ERROR = 'UPDATE_ISSUE_ERROR';

export const ADD_ISSUE_REQUEST = 'ADD_ISSUE_REQUEST';
export const ADD_ISSUE_SUCCESS = 'ADD_ISSUE_SUCCESS';
export const ADD_ISSUE_ERROR = 'ADD_ISSUE_ERROR';

export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';

