export const READ_ISSUES_SUCCESS = 'READ_ISSUES_SUCCESS';
export const READ_ISSUES_ERROR = 'READ_ISSUES_ERROR';
export const READ_ISSUES_REQUEST = 'READ_ISSUES_REQUEST';

export const READ_DEVICE_SUCCESS = 'READ_DEVICE_SUCCESS';
export const READ_DEVICE_ERROR = 'READ_DEVICE_ERROR';
export const READ_DEVICE_REQUEST = 'READ_DEVICE_REQUEST';
